### ISSUE TITLE
can not enable pagination because of Scrollview

### ISSUE THREAD

**Issue by ritikakhelwar** [iNerdStack/react-native-flexible-grid#1]
hi can you please use Flatlist in your npm library so that i can achieve pagination for my data

**Comment by iNerdStack** [comment]
Thanks for bringing this up! 
<code>FlatList</code> was not used because it's designed for linear lists and simple grid layouts based on uniform item sizes and relies on <code>flexbox</code> for layout.

Not adding pagination capability was an oversight, Rest assured, <code>onEndReached</code> and <code>onEndReachedThreshold</code> will be incorporated in our next release to address this.

**Comment by iNerdStack** [comment]
Hello @ritikakhelwar 

A new version [(0.1.7)](https://www.npmjs.com/package/react-native-flexible-grid/v/0.1.7) has been published now with an implementation that covers pagination and also documented in [README.md](https://github.com/iNerdStack/react-native-flexible-grid/blob/main/README.md)

You can see the usage example [here](https://github.com/iNerdStack/react-native-flexible-grid/blob/main/example/src/InfiniteScrollExample.tsx)

**Comment by ritikakhelwar** [comment]
thank you! Its all good now
