### ISSUE TITLE
onEndReached is not working in android device

### ISSUE THREAD

**Issue by ritikakhelwar** [iNerdStack/react-native-flexible-grid#2]
hi can you please check why onEndReached is not working in android device as it is not scrolling in android devices

**Comment by iNerdStack** [comment]
Hello @ritikakhelwar

An example of <code>onEndReached</code> was implemented [here](https://github.com/iNerdStack/react-native-flexible-grid/blob/main/example/src/InstagramExploreExample.tsx) for <code>ResponsiveGrid</code>.

The example has been tested on Android 7 and Android 12 devices, where both scrolling and the <code>onEndReached</code> callback were functioning as intended.

While for <code>FlexGrid</code>, we have <code>onHorizontalEndReached</code> and <code>onVerticalEndReached</code> instead of <code>onEndReached</code> because it's a two-directional ScrollView.

However, you could provide more specifics about your testing environment if the issue persists

Specifically: Device Details, React Native Version, or  Code Snippets

**Comment by ritikakhelwar** [comment]
thanks 😊
