### ISSUE TITLE
Buggy HeaderComponent in ResponsiveGrid

### ISSUE THREAD

**Issue by lucferrario** [iNerdStack/react-native-flexible-grid#4]
I've noticed that my components as i place them as HeaderComponent in my ResponsiveGrid they get shrinked.
The only solution that happened to be working so far was wrapping it inside a view with a fixed minHeight value.

Is there anything that could be done / anything that I'm currently doing wrong?

![image](https://github.com/iNerdStack/react-native-flexible-grid/assets/72550664/944920bc-8061-4485-862c-adf0407df426)

```
<ResponsiveGrid
        data={data}
        renderItem={({ item }) => (
          <View style={{ flex: 1, aspectRatio: 1 }}>
            <Text>{item.id}</Text>
          </View>
        )}
        maxItemsPerColumn={3}
        // style={flatlistStyle}
        HeaderComponent={
          <ProfileCard
            pfp={useAuth().user?.avatar}
            followers={0}
            //inspirations={useAuth().user?.inspirations}
            bio={useAuth().user?.bio}
            location={useAuth().user?.location}
            link={useAuth().user?.link}
            isNew={useAuth().user?.createdAt ? false : true}
            locationSheetRef={locationSheetRef}
            linkSheetRef={linkSheetRef}
          />
        }
      />
```

**Comment by lucferrario** [comment]
Extra note: It would also come really handy to have access to the ContentContainerStyle and HeaderCompoonentStyle props if there is the possibility

**Comment by iNerdStack** [comment]
The header component is wrapped around a <code>View</code> that takes the width and size of its children because the Grid Container arrangement is based on absolute positions. It should also work without you setting a fix height or min height. You can see examples here
[MultiDirectionScrollExample.tsx](https://github.com/iNerdStack/react-native-flexible-grid/blob/main/example/src/MultiDirectionScrollExample.tsx) and [InfiniteScrollExample.tsx](https://github.com/iNerdStack/react-native-flexible-grid/blob/main/example/src/InfiniteScrollExample.tsx)
